### ISSUE TITLE
New link-image option doesn't respect link-target option

### ISSUE THREAD

**Issue by meejle** [Vincenius/bsky-embed#10]
Just a minor thing I spotted -- with `link-target="_blank" link-image="true"`, the image _does_ link to the Bluesky post as expected, but the link _doesn't_ open in a new browser tab.

**Comment by Vincenius** [comment]
Seems to work for me. Do you have an example?

Do you have it in an iframe? Maybe try adding "allow-top-navigation" to the iframe and use `link-target="_parent"`.

**Comment by meejle** [comment]
Weird... It is in an iframe, in theory, but it doesn't work when it's _not_ in the iframe either. 😅

https://www.criticalchicken.com/wp-content/themes/V2-1/bluesky-feed.php

Just tried it in Edge and Firefox (just in case) and the image links are definitely not opening in a new tab/window for me. 🤔

**Comment by meejle** [comment]
That's fixed it, thanks very much! 🥳
