### ISSUE TITLE
Hashtag links formatting strangely, but only on certain posts

### ISSUE THREAD

**Issue by meejle** [Vincenius/bsky-embed#11]
![A screenshot of my issue](https://github.com/Vincenius/bsky-embed/assets/35422415/f051d10c-10fe-4a72-9ca9-773286d69dc0)

Sorry to constantly be a thorn in your side, but I just noticed the hashtag links are somehow "offset" by two characters on my latest post. But seemingly it's _only_ my latest post that's affected. You can use my account @criticalchicken.com on your CodePen demo to see it in action.

**Comment by Vincenius** [comment]
Thanks for the report. Should be fixed in version 0.1.0 :)
