### ISSUE TITLE
Fix Typescript errors

### ISSUE THREAD

**Issue by Vincenius** [Vincenius/bsky-embed#13]
Because I'm lazy, I've ignored a lot of those. Would also be nice to replace all the "any" with proper props.

**Comment by NicoNotAvailable** [comment]
Heya, I would like to help out if thats alrighty. :')

**Comment by Vincenius** [comment]
Sure! Any help is appreciated :)

**Comment by NicoNotAvailable** [comment]
Perfect, I'll start right away

**Comment by Vincenius** [comment]
Done with PR #17 - Thanks a lot @NicoNotAvailable 🔥
