### ISSUE TITLE
Doesn't seem to work for my Bsky account any more

### ISSUE THREAD

**Issue by meejle** [Vincenius/bsky-embed#16]
https://www.criticalchicken.com (iframe, about halfway down the page)  
https://www.criticalchicken.com/wp-content/themes/V2-1/bluesky-feed.php (what the iframe actually shows)

I've also tried this out in your CodePen example, as always.

It works fine with `username="vincentwill.com"` and `username="rachelholliday.bsky.social"` (no relevance; just the username on the first Skeet I happened to see), but with `username="criticalchicken.com"` it just stays on the loading animation.

I don't _think_ it's anything on my end, I've tried a couple of different browsers and devices to make sure.

I love the new updates, by the way! 🥳

**Comment by Vincenius** [comment]
I'll take a look later today or tomorrow :)

**Comment by Vincenius** [comment]
Should be fixed with version 0.1.4
