### ISSUE TITLE
trying and failing in WordPress

### ISSUE THREAD

**Issue by MRMRJ** [Vincenius/bsky-embed#21]
Thank you for your work on this (also gutted about the ironic/tragic state of the social media site formally known as twitter, x) - apologies for the stupid question - just trying out the embed and it shows up wonderfully in the preview toggle of the widget but then delivers only " " in the published page itself... any ideas? 
![image](https://github.com/Vincenius/bsky-embed/assets/18326119/5e7cf38a-3996-44ab-ab6a-312ddd2c3c0e)
![image](https://github.com/Vincenius/bsky-embed/assets/18326119/316b35b7-950b-42d2-a6cc-ce10ca02e82c)
![image](https://github.com/Vincenius/bsky-embed/assets/18326119/101eb344-992f-49a8-b0e4-7c062f289e23)

**Comment by Vincenius** [comment]
Hey @MRMRJ, sorry for the late reply. I just tested it in the WordPress playground, and it seems to work for me.
Maybe there is additional information on what went wrong in the browser dev tools console tab.

<img width="1021" alt="Screenshot 2024-05-30 at 09 19 27" src="https://github.com/Vincenius/bsky-embed/assets/43953403/05dbf1f7-c0b6-4849-a660-a7c8b1959aa5">

![Screenshot 2024-05-30 at 09-18-57 Demo – WordPress Playground](https://github.com/Vincenius/bsky-embed/assets/43953403/838bc725-3874-45e9-b953-b222ee2ddf91)

**Comment by MRMRJ** [comment]
Hi! Please don't worry! This is amazing work and I am delighted if we can all push it on a bit but we're all busy right! I may not get a chance to respond properly for a few days anyway 🙏🎂

**Comment by Vincenius** [comment]
I will close this - let me know if you need further assistance :)
