### ISSUE TITLE
Uncaught SyntaxError: redeclaration of const i

### ISSUE THREAD

**Issue by martymi** [Vincenius/bsky-embed#28]
Hello, really appreciate your efforts on bsky-embed! We are trying this on our wordpress site and I am randomly getting conflicts that have this error. For instance this interferes with the i declaration in GeneratePress premium theme

example conflicting js @
https://nuarrow.com/wp-content/plugins/gp-premium/menu-plus/functions/js/offside.min.js

What's strange is this doesn't occur on every load, it's like every 2-3 loads. This leads to the embed working about half the time, the other half it doesn't work and presents a console error like this.

**Comment by RetroGameDeveloper** [comment]
Hey @martymi I was getting a similar error with the variable "tl", you can fix it by importing with type="module" like so:
```
<script type="module" src="https://cdn.jsdelivr.net/npm/bsky-embed/dist/bsky-embed.es.js" async></script>
```
