### ISSUE TITLE
Unhandled Promise Rejection for some posts

### ISSUE THREAD

**Issue by andreas-zeller** [Vincenius/bsky-embed#31]
Thank you for your work! When embedding my user feed:

```
  <script type="module" src="https://cdn.jsdelivr.net/npm/bsky-embed/dist/bsky-embed.es.js" async></script>
  <bsky-embed
    username="andreaszeller.bsky.social"
    limit="20"
    link-target="_blank"
    link-image="true"
    load-more="true"
  >
  </bsky-embed>
```

the displayed feed stays empty, and the JavaScript console reports

```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.record.facets')
```
![Screenshot 2024-11-26 at 13 57 27](https://github.com/user-attachments/assets/8dd774ac-54d2-413f-b9c9-966d64e38936)

The issue seems to be related to this specific post:

https://bsky.app/profile/dmnk.bsky.social/post/3lbiajmafys2u

As soon as this post is part of my feed, the whole feed no longer shows. If I limit the number of posts such that the above post is no longer included, displaying the feed works again.

Hope that helps, and keep up the good work – Andreas

**Comment by Vincenius** [comment]
Thanks for the detailed bug report. It should be fixed with version 0.2.0.
If it still doesn't render, try including the most recent version (I had some cache issues when testing the bugfix):

```<script type="module" src="https://cdn.jsdelivr.net/npm/bsky-embed@0.2.0/dist/bsky-embed.es.js" async></script>```
