### ISSUE TITLE
add scrolling option

### ISSUE THREAD

**Issue by mihaialexandruteodor** [Vincenius/bsky-embed#33]
Hello!
First of all, thank you for your work on this!

It would be neat to cap the max height of the embed and allow for a scrollbar once the threshold has been reached

**Comment by Vincenius** [comment]
Hey :) This should be possible by setting the height of the container + adding overflow: scroll;

```
<div style="height: 300px; overflow: scroll;">
  <bsky-embed
    username="vincentwill.com"
    limit="5"
    load-more="true"
  >
  </bsky-embed>
</div>
```
