### ISSUE TITLE
Attribute to alter the timestamp date format

### ISSUE THREAD

**Issue by mattortega** [Vincenius/bsky-embed#35]
If we could use an embed element attribute to change the timestamp format from `relative` to:

- `mm/dd/yy`
- `dd/mm/yy`
- `m d, yyyy`

etc.

**Comment by Vincenius** [comment]
Added it in v0.2.2. You can now pass a JSON string to specify the date-format like this:

 
`date-format='{"type":"absolute","locale":"de-DE","options":{"weekday":"long","year":"numeric","month":"long","day":"numeric"}}'`


The type can be "relative" (default) or "absolute". If you choose to use "absolute" you can specify a locale and options based on the [toLocaleDateString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString) function.

**Comment by GwynethLlewelyn** [comment]
... and would it be a pain to add `date-format='{"type":"none"}'` to skip posting the date at all? 🙂 

In my case, I'm rather constrained in how much I can actually display on my blog, so either I figure out a different way of displaying the date, or I'd love to skip it completely...
